// PRODUCTS REQUEST

export const All_PRODUCT_REQUEST = 'All_PRODUCT_REQUEST';
export const All_PRODUCT_SUCCESS = 'All_PRODUCT_SUCCESS';
export const All_PRODUCT_FAILED = 'All_PRODUCT_FAILED';

// PRODUCT DETAIL REQUEST
export const PRODUCT_DETAIL_REQUEST = 'PRODUCT_DETAIL_REQUEST';
export const PRODUCT_DETAIL_SUCCESS = 'PRODUCT_DETAIL_SUCCESS';
export const PRODUCT_DETAIL_FAILED = 'PRODUCT_DETAIL_FAILED';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';



